# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sM7-70SY9QAQYORlTadrwKt_BNXghuQ
"""

# api.py
from fastapi import FastAPI, Query
import psycopg2
from typing import List
from pydantic import BaseModel

app = FastAPI()

class ImageVersion(BaseModel):
    image_name: str
    tag: str
    version: str
    commit: str
    created_at: str
    image_id: str

def fetch_from_db(query, params=()):
    conn = psycopg2.connect(
        dbname="image_tracker",
        user="postgres",
        password="postgres",
        host="localhost"
    )
    cur = conn.cursor()
    cur.execute(query, params)
    rows = cur.fetchall()
    cur.close()
    conn.close()
    return rows

@app.get("/images", response_model=List[ImageVersion])
def list_images():
    rows = fetch_from_db("SELECT image_name, tag, version, commit, created_at, image_id FROM image_versions")
    return [ImageVersion(**dict(zip(ImageVersion.__annotations__.keys(), row))) for row in rows]

@app.get("/images/search", response_model=List[ImageVersion])
def search_images(commit: str = Query(None), image_name: str = Query(None)):
    query = "SELECT image_name, tag, version, commit, created_at, image_id FROM image_versions WHERE 1=1"
    params = []
    if commit:
        query += " AND commit = %s"
        params.append(commit)
    if image_name:
        query += " AND image_name = %s"
        params.append(image_name)
    rows = fetch_from_db(query, tuple(params))
    return [ImageVersion(**dict(zip(ImageVersion.__annotations__.keys(), row))) for row in rows]