# -*- coding: utf-8 -*-
"""scanner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sM7-70SY9QAQYORlTadrwKt_BNXghuQ
"""

pip install docker

# scanner.py
import docker
import datetime
import psycopg2

def extract_metadata(image_name):
    client = docker.from_env()
    image = client.images.get(image_name)
    labels = image.labels
    metadata = {
        "image_name": image_name.split(":")[0],
        "tag": image_name.split(":")[1] if ":" in image_name else "latest",
        "version": labels.get("version", "unknown"),
        "commit": labels.get("commit", "unknown"),
        "created_at": datetime.datetime.now().isoformat(),
        "image_id": image.id
    }
    return metadata

def log_to_postgres(data):
    conn = psycopg2.connect(
        dbname="image_tracker",
        user="postgres",
        password="postgres",
        host="localhost"
    )
    cur = conn.cursor()
    cur.execute("""
        INSERT INTO image_versions (image_name, tag, version, commit, created_at, image_id)
        VALUES (%s, %s, %s, %s, %s, %s)
    """, (data["image_name"], data["tag"], data["version"], data["commit"], data["created_at"], data["image_id"]))
    conn.commit()
    cur.close()
    conn.close()

if __name__ == "__main__":
    image = "my-image:latest"
    metadata = extract_metadata(image)
    log_to_postgres(metadata)
    print(f"Logged metadata: {metadata}")